# Generated by Django 5.2.3 on 2025-06-22 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('merchant_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('rating_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FashionProduct',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('retail_price', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('units_sold', models.IntegerField()),
                ('rating', models.FloatField()),
                ('rating_count', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('theme', models.CharField(max_length=20)),
                ('crawl_month', models.CharField(max_length=10)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion.merchant')),
            ],
        ),
    ]
